version: '3'

services:
  user-web-service:
    container_name: user-web-container
    image: user-web-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Explicitly tell SvelteKit where the app is being served
      # to avoid the "Cross-site POST form submissions are forbidden" error
      # when using form actions with the node adapter
      - ORIGIN=http://localhost:3001
    restart: always
    ports:
      - 3001:3001
