version: '3'

services:
  app-service:
    container_name: app-container
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Explicitly tell SvelteKit where the app is being served
      # to avoid the "Cross-site POST form submissions are forbidden" error
      # when using form actions with the node adapter
      - ORIGIN=http://localhost:5173
    restart: always
    ports:
      - 5173:5173
